server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
    register-with-eureka: false    #自己不注册
  instance:
    instance-id: microservicecloud-consumer-dept-80
    prefer-ip-address: true #显示ip地址